### ISSUE TITLE
Cant Find firefox installation!

### ISSUE THREAD

**Issue by Praveen23445** [OWASP/QRLJacking#110]
Here is what I followed:

1. Installed Virtual box 6.1
2. Installed Kali linux
3. After login, opened terminal, was able to see "kali$kali"
4. downloaded and installed Gekodriver ( as per the instruction from QRLJacking url)
5. Ran all 4 commands mentioned in https://github.com/OWASP/QRLJacking/tree/master/QRLJacker
6. Clonned the git hub QRLJacker
7. installed from requirements.txt file
8. entered "use grabber/whatsapp" command
9. Set the port and host to 80 and 127.0.0.1 respectively
10. set the useragent to default
Till this there were no errors and everything went smooth
when I typed the command "run"
There was an error "Cant find Firefox installation"

Please help me on this.

**Comment by qatux000** [comment]
hey man, i finally figured it out. took me hours upon hours, balls deep in 10 tabs open on chrome just trying to figure out the first 3- seconds of tuturial A LOL but let me tell you what my secret was.

first off i stopped using kali, i'm using parrot os security which (i guess) is more or less the same thing, built the same way. except i find parrot much much MUCH more stable and easy to use than kali. I also stopped using vmware and decided to partition my ssd and go with a hard gui install to dual boot and bruhhh.....game changer. first off its the worst feeling in the world to finally get something working on kali then to realize its only over lan bc of port forwarding in the vm, the hard install fixes these issues. 

first off, from my experience theres two places in the program firefox can be blocked. the first is yours (right after typing in "run") and the second is when you want to view the already captured session. 

when firefox doesnt open in the first half its because qrljacker was not installed using python3.7 and in the correct format.
trust me, hours of trial and error it makes a difference

the second time firefox is blocked can be fixed with this code 
sudo chown root:root .Xauthority 

i have no idea what this does technically, but i think it changes firefox from user permission to root. just make sure you set it back to "sudo chown "userbeforechange:userbeforechange .Xauthority"or you will have a login loop when you reboot

**Comment by qatux000** [comment]
https://streamable.com/q635gt

**Comment by melbadry9** [comment]
@Praveen23445, Do you still have the same issue?

**Comment by qatux000** [comment]
nah i got it all working. i just have too many wifi options in my house so everytime i switch rooms my ip changes and messes up the port forwarding and i just havent had time to play around and make anything dynamic. i'm not sure what my issue was that i posted, but if its the clasic "firefox wont open" sudo chown root:root .Xauthority should do the trick

Sent with [ProtonMail](https://protonmail.com/?utm_campaign=ww-all-2a-mail-pmm_mail-protonmail_signature&utm_source=proton_users&utm_medium=cta&utm_content=sent_with_protonmail_secure_email) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
