### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by elieelias** [OWASP/QRLJacking#36]
I get this error when i try to run the program:

root@kali:~/QRLJacking/QRLJacker# python QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'

I'm using python 3.7 as you can see here:

root@kali:~/QRLJacking/QRLJacker# python
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[3]+  Stopped                 /usr/bin/python3.7

**Comment by SymbianSyMoh** [comment]
Follow the installation guidelines to have all the modules included in "requirements.txt" installed properly because it seems like you are missing "terminaltables" module!

**Comment by elieelias** [comment]
I believe that i’m not missing any step.
Could you comment the link leading to the official guidelines please?

**Comment by SymbianSyMoh** [comment]
Can you please paste the output of "pip install -r requirements.txt" command? Also as stated in issues reporting "**provide the very basic info like your system, python version and the output from the debugging mode.**"

**Comment by elieelias** [comment]
OS name: Kali GNU/Linux Rolling
OS type: 64-bit
Version: Version 3.30.2
Python Version: 3.7

Here is the output of "pip install -r requirements.txt" command:

root@kali:~/QRLJacking/QRLJacker# pip install -r requirements.txt
Collecting terminaltables>=3.1.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting selenium>=3.141.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
    100% |████████████████████████████████| 911kB 402kB/s 
Collecting Pillow>=5.4.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/b6/4b/5adc1109908266554fb978154c797c7d71aba43dd15508d8c1565648f6bc/Pillow-6.0.0-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 233kB/s 
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.10)
Collecting user-agent>=0.1.9 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/c3/ca/15546284f62edfec7666ecb6403a6e77f5db850def37cd36f140d99cce02/user_agent-0.1.9.tar.gz
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from selenium>=3.141.0->-r requirements.txt (line 2)) (1.24)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.12.0)
Building wheels for collected packages: terminaltables, user-agent
  Running setup.py bdist_wheel for terminaltables ... done
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
  Running setup.py bdist_wheel for user-agent ... done
  Stored in directory: /root/.cache/pip/wheels/92/80/3f/5d79277825042f2d4d447f594e3fc046f1e506f2b481d364b2
Successfully built terminaltables user-agent
Installing collected packages: terminaltables, selenium, Pillow, user-agent
  Found existing installation: selenium 3.14.1
    Not uninstalling selenium at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'selenium'. No files were found to uninstall.
  Found existing installation: Pillow 5.3.0
    Not uninstalling pillow at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
Successfully installed Pillow-6.0.0 selenium-3.141.0 terminaltables-3.1.0 user-agent-0.1.9

**Comment by SymbianSyMoh** [comment]
OK, from the command output the "pip" installer is by default installing the requirements for python version 2.7 instead of 3.7 (check the command output there is no mention to python 3.7 because seems like you have both installed in the system).
Try:
`pip3 install -r requirements.txt --force --upgrade`
or
`python3 -m pip install -r requirements.txt --force --upgrade`

**Comment by D4Vinci** [comment]
Okay, from the output I can say you are running the python 2.7 version pip that's why you are getting that error!
If you have installed python 3.7 alone, use this command:
`python3.7 -m pip install -r requirements.txt`
and it will solve your problem.
If not, try this command instead:
`python -m pip install -r requirements.txt`

Try reading the instructions next time before opening issue :smile:

**Comment by D4Vinci** [comment]
lol responded at the same time :laughing: @SymbianSyMoh

**Comment by elieelias** [comment]
Thanks a lot it worked!

**Comment by BlackScorpion10** [comment]
root@kali:~/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'
root@kali:~/QRLJacking/QRLJacker# pip3 install readline
Requirement already satisfied: readline in /usr/local/lib/python3.7/dist-packages (6.2.4.1)
root@kali:~/QRLJacking/QRLJacker# ./QrlJacker.py 
Traceback (most recent call last):
  File "./QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/module.py", line 4, in <module>
    from core import utils,Settings,Cli,db,browser
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 285, in <module>
    self.browsers.append(browser)
NameError: name 'self' is not defined
root@kali:~/QRLJacking/QRLJacker#

**Comment by BlackScorpion10** [comment]
root@kali:~/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'
root@kali:~/QRLJacking/QRLJacker# pip3 install readline
Requirement already satisfied: readline in /usr/local/lib/python3.7/dist-packages (6.2.4.1)
root@kali:~/QRLJacking/QRLJacker# ./QrlJacker.py 
Traceback (most recent call last):
  File "./QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/module.py", line 4, in <module>
    from core import utils,Settings,Cli,db,browser
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 285, in <module>
    self.browsers.append(browser)
NameError: name 'self' is not defined
root@kali:~/QRLJacking/QRLJacker#

**Comment by telugutech07** [comment]
> OK, from the command output the "pip" installer is by default installing the requirements for python version 2.7 instead of 3.7 (check the command output there is no mention to python 3.7 because seems like you have both installed in the system).
> Try:
> `pip3 install -r requirements.txt --force`
> or
> `python3 -m pip install -r requirements.txt --force`

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting terminaltables>=3.1.0 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
  Could not fetch URL https://pypi.org/simple/terminaltables/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/terminaltables/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement terminaltables>=3.1.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for terminaltables>=3.1.0 (from -r requirements.txt (line 1))
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping




its saying that after that  command

**Comment by attack101** [comment]
python3 -m pip install -r requirements.txt --force
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/
Could not fetch URL https://pypi.org/simple/terminaltables/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/terminaltables/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement terminaltables>=3.1.0 (from versions: none)
ERROR: No matching distribution found for terminaltables>=3.1.0
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by fffff515** [comment]
hello, i'm having a problem on startup. When you run the program, it works and does not give errors, but at the same time I don’t get QR-code
