### ISSUE TITLE
Error when trying to install requirements

### ISSUE THREAD

**Issue by miguelng02** [OWASP/QRLJacking#82]
Please help

I get this error when trying to install the requirements:

**kali@kali:~/Desktop/QRLJacking/QRLJacker$ python3 QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'**

---------------------------------------------------------------------------------------

Yes i did follow the instructions ... Running Python3.7 and Python2.7(both)

Please help me!

**Comment by omarito444** [comment]
try using pip3 install -r requirements.txt

**Comment by blackcrush** [comment]
even i am getting same error can you please assist me .......

root@kali:/home/kali/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/home/kali/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by jeyharish** [comment]
when i install requirments its getting error please help me 


root@kali:~/QRLJacking/QRLJacker# pip3 install -r requirements.txt
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting terminaltables>=3.1.0 (from -r requirements.txt (line 1))
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                                             
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                                             
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                                             
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                                             
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                                             
  Could not fetch URL https://pypi.org/simple/terminaltables/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/terminaltables/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement terminaltables>=3.1.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for terminaltables>=3.1.0 (from -r requirements.txt (line 1))
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by pavan9866** [comment]
Try pip3

**Comment by melbadry9** [comment]
Please reinstall Python3. It’s not a bug in our code.

**Comment by blkhourse** [comment]
me to please help 
──(root💀kali)-[/home/kali/QRLJacking/QRLJacker]
└─# python3 QrlJacker.py                        
Traceback (most recent call last):
  File "QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/home/kali/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'
